dbt_training:
  outputs:
    dev:
      account: yl45797.east-us-2.azure
      database: analytics_077
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_077
      schema: dbt_fb
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_077
    ci:
      account: yl45797.east-us-2.azure
      database: analytics_077
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_077
      schema: dbt_ci
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_077
    prod:
      account: yl45797.east-us-2.azure
      database: analytics_077
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_077
      schema: dbt_prod
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_077
  target: dev
